import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Header from '@/app/_components/Header';
import "@/app/_assets/globals.css";
import { RequestMaintenanceProvider } from "@/app/_stores/RequestMaintenanceStore";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased flex flex-col items-center h-screen`}
      >
        <RequestMaintenanceProvider>
          <Header />
          {children}
        </RequestMaintenanceProvider>
      </body>
    </html>
  );
}
